version: '3.4'

services:

  patientsregistry.web:
    build:
      context: .
      dockerfile: PatientsRegistry.Web/Dockerfile
    ports:
      - 5500:80

  patientsregistry.api:
    build:
      context: .
      dockerfile: PatientsRegistry.API/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - elasticsearch
    restart: always
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
      
  elasticsearch:
    image: elasticsearch:6.6.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    restart: always